// Sticker Quest design tokens per category / bonus item.
// `art` names a PNG in /public/art (generated by scripts/generate-art.mjs);
// StickerArt falls back to `emoji` when the PNG isn't there.

export interface CategoryTheme {
  main: string;
  edge: string;
  soft: string;
  text: string;
  btn: string;
  art: string;
  emoji: string;
}

export const categoryTheme: Record<string, CategoryTheme> = {
  faith: {
    main: '#FFB020',
    edge: '#D98F00',
    soft: '#FFF4D9',
    text: '#8A5B00',
    btn: 'btn-sun',
    art: 'cat-faith',
    emoji: '🏮',
  },
  choices: {
    main: '#7A6CF0',
    edge: '#5A4BD8',
    soft: '#ECE9FF',
    text: '#453AA4',
    btn: 'btn-grape',
    art: 'cat-choices',
    emoji: '🧭',
  },
  service: {
    main: '#FF6B6B',
    edge: '#E04848',
    soft: '#FFE7E4',
    text: '#A83232',
    btn: 'btn-coral',
    art: 'cat-love',
    emoji: '💝',
  },
  scriptures: {
    main: '#2FBF71',
    edge: '#22995A',
    soft: '#DFF6E9',
    text: '#157A47',
    btn: 'btn-leaf',
    art: 'cat-scriptures',
    emoji: '📖',
  },
  community: {
    main: '#38B6FF',
    edge: '#1E93DB',
    soft: '#E0F3FF',
    text: '#0F6FA8',
    btn: 'btn-sky',
    art: 'cat-plan',
    emoji: '🌅',
  },
};

export const fallbackTheme: CategoryTheme = {
  main: '#FFB020',
  edge: '#D98F00',
  soft: '#FFF4D9',
  text: '#8A5B00',
  btn: 'btn-sun',
  art: 'mascot',
  emoji: '⭐',
};

export function getCategoryTheme(id: string): CategoryTheme {
  return categoryTheme[id] ?? fallbackTheme;
}

export const bonusArt: Record<string, { art: string; emoji: string }> = {
  'bonus-1': { art: 'bonus-drop', emoji: '💧' },
  'bonus-2': { art: 'bonus-dove', emoji: '🕊️' },
  'bonus-3': { art: 'bonus-heart', emoji: '❤️' },
  'bonus-4': { art: 'bonus-ring', emoji: '♾️' },
};
